[package]
name = "leet_beautiful_subsets"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = "0.7.0"
rand = "0.9.2"

[[bench]]
name = "my_benchmark"
harness = false

[profile.bench]
debug = false

[profile.release]
debug = false
