[package]
name = "leet_beautiful_subsets"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = "0.7.0"
rand = "0.9.2"
rustc-hash = "2.1.1"

[[bench]]
name = "my_benchmark"
harness = false

[profile.bench]
debug = 1

[profile.release]
debug = 1
